Repository duplocloud/actions, pull requests merged in 2024-07, with the labels that each got.

#31 disable buildx
  build-image/action.yml
Labels: enhancement, Review effort [1-5]: 3

#32 Handle race conditions on node startup and fast pods
  k8s-job/README.md
  k8s-job/action.yml
Labels: documentation, enhancement, Review effort [1-5]: 2

#33 Build image updates
  build-image/action.yml
Labels: enhancement, configuration changes, Review effort [1-5]: 4
