Repository duplocloud/actions, pull requests merged in 2024-02, with the labels that each got.

#5 Node Warning Fix
  setup/README.md
  setup/action.yml
Labels: enhancement, Review effort [1-5]: 1

#7 added the k8s job runner
  k8s-job/README.md
  k8s-job/action.yml
Labels: enhancement, Review effort [1-5]: 2

#9 chore(docs): remove prompt response
  setup/README.md
Labels: documentation, Review effort [1-5]: 1

#8 MultiCloud style
  setup/README.md
  setup/action.yml
  terraform-exec/action.yml
  terraform-module/README.md
  terraform-module/action.yml
Labels: documentation, enhancement, Review effort [1-5]: 2, configuration changes

#10 K8s job status update
  k8s-job/action.yml
Labels: enhancement, Review effort [1-5]: 2
