Repository duplocloud/actions, pull requests merged in 2024-03, with the labels that each got.

#12 git bump action
  build-image/action.yml
  git-bump/README.md
  git-bump/action.yml
Labels: enhancement, Review effort [1-5]: 2

#13 DUPLO-15619 upgrade actions
  .github/dependabot.yml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#28 fix input name mismatch on name input
  update-image/action.yml
Labels: Review effort [1-5]: 1, bug_fix
